[package]
name = "chaincue-real-estate-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["api", "migration"]

[dependencies]
chaincue-real-estate-rust-api = { path = "api" }
