# change 10.244.0.44:5432
apiVersion: v1
kind: ConfigMap
metadata:
  name: chaincue-real-estate-rust1-config
data:
  DATABASE_URL: "postgres://admin:admin@10.244.0.67:5432/chaincue-real-estate-rust-postgres"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaincue-real-estate-rust1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaincue-real-estate-rust1
  template:
    metadata:
      labels:
        app: chaincue-real-estate-rust1
    spec:
      containers:
        - name: chaincue-real-estate-rust1
          image: backend-api-rust:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: chaincue-real-estate-rust1-config
---

apiVersion: v1
kind: Service
metadata:
  name: chaincue-real-estate-rust1
spec:
  selector:
    app: chaincue-real-estate-rust1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chaincue-real-estate-rust1-ingress
spec:
  rules:
    - host: local.chaincue.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chaincue-real-estate-rust1
                port:
                  number: 8080
