//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::brokers::Entity as Brokers;
pub use super::countries::Entity as Countries;
pub use super::house_images::Entity as HouseImages;
pub use super::houses::Entity as Houses;
